---
 - hosts: ubuntu
   gather_facts: yes
   become: true
   become_method: su
   become_user: root
   tasks:
   - name: Create users and groups
     block:
       - name: Create tizu group
         group:
              name: tizu
              state: present
       - name: Create ansible group
         group:
              name: ansible
              state: present
       - name: Create tizu user
         user:
              name: tizu
              shell: /bin/bash
              groups: tizu,adm,cdrom,sudo,dip,plugdev,lxd
       - name: Add tizu user to the sudoers
         copy:
              dest: "/etc/sudoers.d/tizu"
              content: "tizu  ALL=(ALL)  NOPASSWD: ALL"
       - name: Deploy SSH Key to tizu user
         authorized_key: user=tizu
                         key="{{ lookup('file', '/home/tizu/.ssh/id_ed25519.pub') }}"
                         state=present
       - name: Create ansible user
         user:
              name: ansible
              shell: /bin/bash
              groups: ansible,adm,cdrom,sudo,dip,plugdev,lxd
       - name: Add ansible user to the sudoers
         copy:
              dest: "/etc/sudoers.d/ansible"
              content: "ansible  ALL=(ALL)  NOPASSWD: ALL"
       - name: Deploy SSH Key to ansible user
         authorized_key: user=ansible
                         key="{{ lookup('file', '/home/tizu/.ssh/id_ed25519.pub') }}"
                         state=present
