---
 - hosts: windows
   gather_facts: true
   tasks:
   - name: Windows updates
     block:
       - name: Install Windows updates
         win_updates:
           category_names:
            - CriticalUpdates
            - SecurityUpdates
            - UpdateRollups
            - Updates
            - DefinitionUpdates 
           reboot: yes
           log_path:  C:/ansible_windows_updates.log        
         register: update_results
       - name: Update results
         debug:
           msg: "Update results: {{ update_results }}"
